'use client';

import { RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useMotivations } from '@/lib/hooks/useMotivations';
import { useRegenerateMotivations } from '@/lib/hooks/useProducts';
import { MotivationCard } from '@/components/motivations/MotivationCard';
import { LoadingSpinner } from '@/components/shared/LoadingSpinner';
import { EmptyState } from '@/components/shared/EmptyState';
import { ErrorState } from '@/components/shared/ErrorState';

export default function MotivationsPage({ params }: { params: { id: string } }) {
  const { id } = params;
  const { data, isLoading, isError, refetch } = useMotivations(id);
  const { mutateAsync: regen, isPending } = useRegenerateMotivations(id);

  const handleRegen = async () => {
    try {
      await regen();
      toast.success('Regenerating motivations...');
    } catch {
      toast.error('Failed to regenerate motivations');
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">AI Motivation Analysis</h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Psychographic profiles generated by AI for targeting
          </p>
        </div>
        <button
          onClick={handleRegen}
          disabled={isPending}
          className="flex items-center gap-1.5 px-3 py-2 border border-slate-200 text-slate-600 text-sm font-medium rounded-lg hover:bg-slate-50 transition disabled:opacity-60"
        >
          <RefreshCw size={14} className={isPending ? 'animate-spin' : ''} />
          Regenerate
        </button>
      </div>

      {isLoading ? (
        <div className="flex items-center justify-center h-64">
          <LoadingSpinner size="lg" label="Loading motivations..." />
        </div>
      ) : isError ? (
        <ErrorState
          title="Failed to load motivations"
          message="The pipeline may not have reached this step yet."
          onRetry={() => void refetch()}
        />
      ) : !data?.categories.length ? (
        <EmptyState
          title="No motivations generated yet"
          description="The AI motivation analysis runs in the first pipeline step."
        />
      ) : (
        <>
          <p className="text-sm text-slate-500">
            {data.total} motivation categories identified
          </p>
          <div className="space-y-4">
            {data.categories
              .sort((a, b) => a.sort_order - b.sort_order)
              .map((cat, i) => (
                <MotivationCard key={cat.id} category={cat} index={i} />
              ))}
          </div>
        </>
      )}
    </div>
  );
}
