"""002_phase_c_nlp_tables

Revision ID: 29cdcf7af02d
Revises: ca1afd1017a3
Create Date: 2026-06-02 16:02:08.800700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29cdcf7af02d'
down_revision: Union[str, None] = 'ca1afd1017a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding_type', sa.String(length=20), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['discovered_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'embedding_type', name='uq_user_embedding_type')
    )
    op.create_index(op.f('ix_user_embeddings_user_id'), 'user_embeddings', ['user_id'], unique=False)
    op.create_table('user_nlp_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('empath_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bertopic_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bertopic_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spacy_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interest_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword_frequency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary_richness', sa.Float(), nullable=True),
    sa.Column('avg_sentence_length', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['discovered_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_nlp_features')
    )
    op.create_index(op.f('ix_user_nlp_features_user_id'), 'user_nlp_features', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nlp_features_user_id'), table_name='user_nlp_features')
    op.drop_table('user_nlp_features')
    op.drop_index(op.f('ix_user_embeddings_user_id'), table_name='user_embeddings')
    op.drop_table('user_embeddings')
    # ### end Alembic commands ###
