"""006_product_ocean_similar_products

Creates two new tables:
  - product_ocean_profiles : one aggregated OCEAN vector per product
  - similar_products       : similar products found for each product via OCEAN similarity

Adds new columns to three existing tables:
  - discovery_jobs    : similar_products_searched (audit log of which similar products
                        were included in each discovery run)
  - discovered_users  : discovery_source (primary vs similar_product)
                        similar_product_id (which similar product triggered discovery)
  - lead_matches      : product_ocean_score (supplementary score vs product-level OCEAN)

Revision ID: a1b2c3d4e5f6
Revises: e2f4b8c1d9a5
Create Date: 2026-06-05 00:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "e2f4b8c1d9a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── 1. product_ocean_profiles ─────────────────────────────────────────────
    # Stores the single aggregated OCEAN vector for a product.
    # Derived by averaging all motivation OCEAN profiles after motivation
    # generation completes. Used as the matching target in Step 7 and as
    # the source vector for similar product discovery in Step 4.
    op.create_table(
        "product_ocean_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("openness", sa.Float(), nullable=False),
        sa.Column("conscientiousness", sa.Float(), nullable=False),
        sa.Column("extraversion", sa.Float(), nullable=False),
        sa.Column("agreeableness", sa.Float(), nullable=False),
        sa.Column("neuroticism", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="50.0"),
        sa.Column(
            "derivation_method",
            sa.String(20),
            nullable=False,
            server_default="motivation_average",
        ),
        sa.Column("component_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", name="uq_product_ocean_profile_product"),
    )
    op.create_index(
        "ix_product_ocean_profiles_product_id",
        "product_ocean_profiles",
        ["product_id"],
        unique=True,
    )

    # ── 2. similar_products ───────────────────────────────────────────────────
    # Each row is one similar product found for a registered product.
    # The LLM generates these with their own OCEAN profiles; we then compute
    # cosine similarity to the product's OCEAN vector and keep the top N.
    # The discovery_keywords list drives expanded keyword search in Step 5.
    #
    # NOTE: created AFTER product_ocean_profiles because discovered_users will
    # later add an FK here; the table must exist before that ALTER TABLE.
    op.create_table(
        "similar_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("similar_product_name", sa.String(255), nullable=False),
        sa.Column("similar_product_category", sa.String(100), nullable=True),
        sa.Column("similar_product_description", sa.Text(), nullable=True),
        # OCEAN profile of the similar product (0-100 scale, generated by LLM)
        sa.Column("openness", sa.Float(), nullable=True),
        sa.Column("conscientiousness", sa.Float(), nullable=True),
        sa.Column("extraversion", sa.Float(), nullable=True),
        sa.Column("agreeableness", sa.Float(), nullable=True),
        sa.Column("neuroticism", sa.Float(), nullable=True),
        # How similar this product's OCEAN is to the source product's OCEAN
        sa.Column("similarity_score", sa.Float(), nullable=True),
        # Keywords to use when searching discussions about this similar product
        sa.Column(
            "discovery_keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default="true",
        ),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_similar_products_product_id",
        "similar_products",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_similar_products_is_active",
        "similar_products",
        ["is_active"],
        unique=False,
    )

    # ── 3. discovery_jobs — audit column ──────────────────────────────────────
    # Records which similar products and their keywords were searched in this
    # specific job run. Purely informational — used for audit and debugging.
    op.add_column(
        "discovery_jobs",
        sa.Column(
            "similar_products_searched",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )

    # ── 4. discovered_users — source attribution columns ──────────────────────
    # discovery_source  : was this user found via the primary product's keywords
    #                     or via a similar product's keywords?
    # similar_product_id: which specific similar product triggered this discovery
    #                     (nullable — NULL when discovery_source = 'primary')
    op.add_column(
        "discovered_users",
        sa.Column(
            "discovery_source",
            sa.String(20),
            nullable=False,
            server_default="primary",
        ),
    )
    op.add_column(
        "discovered_users",
        sa.Column(
            "similar_product_id",
            sa.UUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_discovered_users_similar_product",
        "discovered_users",
        "similar_products",
        ["similar_product_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_discovered_users_similar_product_id",
        "discovered_users",
        ["similar_product_id"],
        unique=False,
    )

    # ── 5. lead_matches — supplementary product-level score ───────────────────
    # Stores the OCEAN distance between this lead's personality and the
    # product-level OCEAN profile. Informational only — does NOT affect
    # the final_score formula. Allows clients to see how well a lead aligns
    # with the product as a whole, not just the best-matching persona.
    op.add_column(
        "lead_matches",
        sa.Column("product_ocean_score", sa.Float(), nullable=True),
    )


def downgrade() -> None:
    # Reverse in exact opposite order of upgrade to avoid FK violations
    op.drop_column("lead_matches", "product_ocean_score")

    op.drop_index(
        "ix_discovered_users_similar_product_id",
        table_name="discovered_users",
    )
    op.drop_constraint(
        "fk_discovered_users_similar_product",
        "discovered_users",
        type_="foreignkey",
    )
    op.drop_column("discovered_users", "similar_product_id")
    op.drop_column("discovered_users", "discovery_source")

    op.drop_column("discovery_jobs", "similar_products_searched")

    op.drop_index("ix_similar_products_is_active", table_name="similar_products")
    op.drop_index("ix_similar_products_product_id", table_name="similar_products")
    op.drop_table("similar_products")

    op.drop_index(
        "ix_product_ocean_profiles_product_id",
        table_name="product_ocean_profiles",
    )
    op.drop_table("product_ocean_profiles")
