"""001_baseline_existing_tables

Revision ID: ca1afd1017a3
Revises: 
Create Date: 2026-06-02 14:24:51.707620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca1afd1017a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('users_discovered', sa.Integer(), nullable=False),
    sa.Column('users_content_collected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_jobs_product_id'), 'discovery_jobs', ['product_id'], unique=False)
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('signals_extracted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_jobs_product_id'), 'enrichment_jobs', ['product_id'], unique=False)
    op.create_table('discovered_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('discovery_job_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_confidence', sa.String(length=20), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_collected', sa.Boolean(), nullable=False),
    sa.Column('nlp_processed', sa.Boolean(), nullable=False),
    sa.Column('ocean_scored', sa.Boolean(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', 'discovery_job_id', name='uq_discovered_user_platform_job')
    )
    op.create_index(op.f('ix_discovered_users_discovery_job_id'), 'discovered_users', ['discovery_job_id'], unique=False)
    op.create_index(op.f('ix_discovered_users_product_id'), 'discovered_users', ['product_id'], unique=False)
    op.create_table('product_enrichment_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('enrichment_job_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=30), nullable=False),
    sa.Column('signal_text', sa.Text(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=False),
    sa.Column('ocean_hint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrichment_job_id'], ['enrichment_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_enrichment_signals_product_id'), 'product_enrichment_signals', ['product_id'], unique=False)
    op.create_table('user_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['discovered_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_content_user_id'), 'user_content', ['user_id'], unique=False)
    # server_default required so existing rows get a valid value immediately.
    op.add_column('motivation_categories', sa.Column(
        'enrichment_context',
        postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
        server_default=sa.text("'{}'::jsonb"),
    ))
    op.add_column('products', sa.Column(
        'enrichment_status',
        sa.String(length=20),
        nullable=False,
        server_default=sa.text("'none'"),
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'enrichment_status')
    op.drop_column('motivation_categories', 'enrichment_context')
    op.drop_index(op.f('ix_user_content_user_id'), table_name='user_content')
    op.drop_table('user_content')
    op.drop_index(op.f('ix_product_enrichment_signals_product_id'), table_name='product_enrichment_signals')
    op.drop_table('product_enrichment_signals')
    op.drop_index(op.f('ix_discovered_users_product_id'), table_name='discovered_users')
    op.drop_index(op.f('ix_discovered_users_discovery_job_id'), table_name='discovered_users')
    op.drop_table('discovered_users')
    op.drop_index(op.f('ix_enrichment_jobs_product_id'), table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    op.drop_index(op.f('ix_discovery_jobs_product_id'), table_name='discovery_jobs')
    op.drop_table('discovery_jobs')
    # ### end Alembic commands ###
